import type { CatalogoData } from "@/types";

export const catalogoInicial: CatalogoData = {
  categorias: [
    "Análisis de la Industria",
    "Geomarketing",
    "Análisis en campo",
    "Encuestas",
    "Entrevistas",
    "Focus Group",
    "Benchmarking",
    "Búsqueda de locales",
  ],
  servicios: [
    // ── Análisis de la Industria ────────────────────────────────────────────
    {
      id: "ai-01",
      categoria: "Análisis de la Industria",
      nombre: "Análisis de industria completo",
      descripcion: "Análisis integral del sector, tendencias, actores clave y entorno competitivo.",
      desglose: "Investigación documental + informe ejecutivo",
      precio: 5000,
      unidad: "proyecto",
      aporte_pm: 1000,
    },
    {
      id: "ai-02",
      categoria: "Análisis de la Industria",
      nombre: "Análisis de competencia directa",
      descripcion: "Identificación y análisis de competidores directos del cliente.",
      desglose: "Hasta 5 competidores",
      precio: 3500,
      unidad: "proyecto",
      aporte_pm: 800,
    },
    {
      id: "ai-03",
      categoria: "Análisis de la Industria",
      nombre: "Análisis PESTEL",
      descripcion: "Evaluación de factores políticos, económicos, sociales, tecnológicos, ecológicos y legales.",
      desglose: "Informe PESTEL con recomendaciones",
      precio: 3000,
      unidad: "proyecto",
      aporte_pm: 700,
    },
    {
      id: "ai-04",
      categoria: "Análisis de la Industria",
      nombre: "Análisis de tendencias de mercado",
      descripcion: "Estudio de tendencias actuales y proyecciones del mercado objetivo.",
      precio: 2500,
      unidad: "proyecto",
      aporte_pm: 600,
    },

    // ── Geomarketing ────────────────────────────────────────────────────────
    {
      id: "geo-01",
      categoria: "Geomarketing",
      nombre: "Análisis de zona de influencia",
      descripcion: "Delimitación y análisis de la zona de influencia de un punto de venta.",
      desglose: "Mapa + informe de radio de influencia",
      precio: 4500,
      unidad: "punto",
      aporte_pm: 1000,
    },
    {
      id: "geo-02",
      categoria: "Geomarketing",
      nombre: "Mapa de densidad poblacional",
      descripcion: "Visualización geoespacial de concentración demográfica en el área de estudio.",
      precio: 3500,
      unidad: "área",
      aporte_pm: 800,
    },
    {
      id: "geo-03",
      categoria: "Geomarketing",
      nombre: "Análisis de competencia georreferenciada",
      descripcion: "Mapeo de competidores en el área de interés con análisis de accesibilidad.",
      precio: 4000,
      unidad: "área",
      aporte_pm: 900,
    },
    {
      id: "geo-04",
      categoria: "Geomarketing",
      nombre: "Scoring de ubicaciones",
      descripcion: "Evaluación y ranking de ubicaciones potenciales para apertura de puntos.",
      precio: 5000,
      unidad: "estudio",
      aporte_pm: 1000,
    },
    {
      id: "geo-05",
      categoria: "Geomarketing",
      nombre: "Isócronas y accesibilidad",
      descripcion: "Análisis de tiempo-distancia y accesibilidad desde puntos de interés.",
      precio: 3000,
      unidad: "punto",
      aporte_pm: 700,
    },

    // ── Análisis en campo ───────────────────────────────────────────────────
    {
      id: "ac-01",
      categoria: "Análisis en campo",
      nombre: "Mystery Shopper",
      descripcion: "Evaluación de la experiencia de compra desde la perspectiva del cliente incógnito.",
      desglose: "Reporte por visita",
      precio: 1200,
      unidad: "visita",
      aporte_pm: 1000,
    },
    {
      id: "ac-02",
      categoria: "Análisis en campo",
      nombre: "Auditoría de punto de venta",
      descripcion: "Revisión de presencia de marca, exhibición y ejecución en PDV.",
      precio: 800,
      unidad: "PDV",
      aporte_pm: 800,
    },
    {
      id: "ac-03",
      categoria: "Análisis en campo",
      nombre: "Aforo / conteo de tráfico",
      descripcion: "Conteo de afluencia peatonal o vehicular en puntos estratégicos.",
      precio: 600,
      unidad: "punto/día",
      aporte_pm: 700,
    },
    {
      id: "ac-04",
      categoria: "Análisis en campo",
      nombre: "Observación etnográfica",
      descripcion: "Observación no participante del comportamiento del consumidor en contexto natural.",
      precio: 5000,
      unidad: "proyecto",
      aporte_pm: 1000,
    },

    // ── Encuestas ───────────────────────────────────────────────────────────
    {
      id: "enc-01",
      categoria: "Encuestas",
      nombre: "Encuesta estándar",
      descripcion: "Cuestionario estructurado aplicado en campo por encuestadores.",
      desglose: "Precio por encuesta aplicada",
      precio: 70,
      unidad: "encuesta",
      aporte_pm: 800,
    },
    {
      id: "enc-02",
      categoria: "Encuestas",
      nombre: "Encuesta online (CAWI)",
      descripcion: "Cuestionario digital autoadministrado, reclutamiento y plataforma incluidos.",
      precio: 90,
      unidad: "encuesta",
      aporte_pm: 600,
    },
    {
      id: "enc-03",
      categoria: "Encuestas",
      nombre: "Encuesta telefónica (CATI)",
      descripcion: "Encuesta aplicada vía llamada telefónica.",
      precio: 110,
      unidad: "encuesta",
      aporte_pm: 700,
    },
    {
      id: "enc-04",
      categoria: "Encuestas",
      nombre: "Diseño de cuestionario",
      descripcion: "Elaboración y validación de instrumento de medición.",
      precio: 3000,
      unidad: "proyecto",
      aporte_pm: 500,
    },
    {
      id: "enc-05",
      categoria: "Encuestas",
      nombre: "Panel de consumidores",
      descripcion: "Reclutamiento y aplicación de encuesta a panel curado de perfiles específicos.",
      precio: 150,
      unidad: "panelista",
      aporte_pm: 800,
    },

    // ── Entrevistas ─────────────────────────────────────────────────────────
    {
      id: "ent-01",
      categoria: "Entrevistas",
      nombre: "Entrevista a profundidad",
      descripcion: "Entrevista semiestructurada individual con análisis cualitativo.",
      desglose: "Incluye reclutamiento, aplicación y análisis",
      precio: 2500,
      unidad: "entrevista",
      aporte_pm: 800,
    },
    {
      id: "ent-02",
      categoria: "Entrevistas",
      nombre: "Entrevista a expertos (IDI)",
      descripcion: "Entrevistas a líderes de industria o expertos temáticos.",
      precio: 3500,
      unidad: "entrevista",
      aporte_pm: 900,
    },
    {
      id: "ent-03",
      categoria: "Entrevistas",
      nombre: "Entrevista etnográfica en hogar",
      descripcion: "Entrevista contextual realizada en el entorno natural del informante.",
      precio: 3000,
      unidad: "entrevista",
      aporte_pm: 800,
    },
    {
      id: "ent-04",
      categoria: "Entrevistas",
      nombre: "Reclutamiento de perfil específico",
      descripcion: "Identificación y selección de participantes con perfil definido.",
      precio: 800,
      unidad: "participante",
      aporte_pm: 500,
    },

    // ── Focus Group ─────────────────────────────────────────────────────────
    {
      id: "fg-01",
      categoria: "Focus Group",
      nombre: "Focus Group estándar",
      descripcion: "Sesión de grupo focal con 8-10 participantes y moderador experto.",
      desglose: "Incluye reclutamiento, sala, moderación y relatoría",
      precio: 18000,
      unidad: "sesión",
      aporte_pm: 500,
    },
    {
      id: "fg-02",
      categoria: "Focus Group",
      nombre: "Focus Group online",
      descripcion: "Sesión grupal virtual con plataforma de videoconferencia especializada.",
      precio: 14000,
      unidad: "sesión",
      aporte_pm: 400,
    },
    {
      id: "fg-03",
      categoria: "Focus Group",
      nombre: "Focus Group de segmento específico",
      descripcion: "Grupo focal con reclutamiento de perfil difícil o de alta especificidad.",
      precio: 22000,
      unidad: "sesión",
      aporte_pm: 600,
    },
    {
      id: "fg-04",
      categoria: "Focus Group",
      nombre: "Reclutamiento para Focus Group",
      descripcion: "Reclutamiento exclusivo de participantes para sesiones de grupo.",
      precio: 500,
      unidad: "participante",
      aporte_pm: 300,
    },
    {
      id: "fg-05",
      categoria: "Focus Group",
      nombre: "Análisis semiótico de material",
      descripcion: "Análisis de lenguaje, símbolos y percepciones en material de comunicación.",
      precio: 8000,
      unidad: "proyecto",
      aporte_pm: 500,
    },

    // ── Benchmarking ────────────────────────────────────────────────────────
    {
      id: "bm-01",
      categoria: "Benchmarking",
      nombre: "Benchmarking competitivo",
      descripcion: "Comparación de métricas clave frente a competidores del sector.",
      desglose: "Hasta 5 competidores, 3 dimensiones",
      precio: 6000,
      unidad: "estudio",
      aporte_pm: 1000,
    },
    {
      id: "bm-02",
      categoria: "Benchmarking",
      nombre: "Benchmarking de precios",
      descripcion: "Monitoreo y comparación de precios de competidores en mercado.",
      precio: 4000,
      unidad: "estudio",
      aporte_pm: 800,
    },
    {
      id: "bm-03",
      categoria: "Benchmarking",
      nombre: "Benchmarking de comunicación",
      descripcion: "Análisis comparativo de estrategias de comunicación y posicionamiento.",
      precio: 5000,
      unidad: "estudio",
      aporte_pm: 900,
    },
    {
      id: "bm-04",
      categoria: "Benchmarking",
      nombre: "Benchmarking de experiencia de cliente",
      descripcion: "Comparación de indicadores de satisfacción y CX frente a la competencia.",
      precio: 7000,
      unidad: "estudio",
      aporte_pm: 1000,
    },

    // ── Búsqueda de locales ─────────────────────────────────────────────────
    {
      id: "bl-01",
      categoria: "Búsqueda de locales",
      nombre: "Prospección de locales comerciales",
      descripcion: "Búsqueda activa y evaluación de espacios para apertura según criterios del cliente.",
      desglose: "Incluye visitas, ficha técnica y mapa",
      precio: 8000,
      unidad: "zona",
      aporte_pm: 1000,
    },
    {
      id: "bl-02",
      categoria: "Búsqueda de locales",
      nombre: "Evaluación de local específico",
      descripcion: "Análisis de viabilidad comercial de un local candidato.",
      precio: 4000,
      unidad: "local",
      aporte_pm: 800,
    },
  ],
};
