import type { CatalogoData } from "@/types";

export const catalogoInicial: CatalogoData = {
  categorias: [
    "Análisis de la industria",
    "Geomarketing",
    "Análisis en campo",
    "Encuestas",
    "Entrevistas",
    "Focus Group",
    "Benchmarking",
    "Búsqueda y recomendación PDV",
  ],
  servicios: [
    // ── Análisis de la industria ────────────────────────────────────────────
    {
      id: "ai-01",
      categoria: "Análisis de la industria",
      nombre: "Dimensionamiento y Salud de la Industria",
      descripcion: "Calcula cuánto vale el mercado total y su tasa de crecimiento (CAGR) para saber si el sector se está expandiendo o contrayendo.",
      desglose: "Por análisis",
      precio: 5000,
      unidad: "análisis",
      aporte_pm: 1000,
    },
    {
      id: "ai-02",
      categoria: "Análisis de la industria",
      nombre: "Inteligencia de Comercio Exterior (Aduanas)",
      descripcion: "Rastrea importaciones y exportaciones masivas para identificar saturación de oferta, entrada de productos extranjeros o costos de insumos.",
      desglose: "Por análisis",
      precio: 5000,
      unidad: "análisis",
      aporte_pm: 1000,
    },
    {
      id: "ai-03",
      categoria: "Análisis de la industria",
      nombre: "Diagnóstico de Entorno Macro (PESTEL)",
      descripcion: "Evalúa factores externos incontrolables (Inflación, Tipo de Cambio, Regulaciones) que impactan directamente la rentabilidad o las ventas.",
      desglose: "Por análisis",
      precio: 5000,
      unidad: "análisis",
      aporte_pm: 1000,
    },
    {
      id: "ai-04",
      categoria: "Análisis de la industria",
      nombre: "Análisis de Tendencias de Consumo y Demanda Digital",
      descripcion: "Investiga cambios en hábitos de compra y volúmenes de búsqueda online (Google Trends/Keywords) para explicar si el interés del usuario ha caído.",
      desglose: "Por análisis",
      precio: 5000,
      unidad: "análisis",
      aporte_pm: 1000,
    },

    // ── Geomarketing ────────────────────────────────────────────────────────
    {
      id: "geo-01",
      categoria: "Geomarketing",
      nombre: "Análisis de Vocación Comercial",
      descripcion: "Dispone de inmueble, sin modelo. Identifica el giro comercial ideal basado en la oferta y demanda de la zona.",
      desglose: "Por ciudad",
      precio: 12000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
    {
      id: "geo-02",
      categoria: "Geomarketing",
      nombre: "Factibilidad de Modelo de Negocio",
      descripcion: "Dispone de inmueble y modelo. Determina si la ubicación soporta técnica, sociodemográfica y comercialmente el negocio propuesto.",
      desglose: "Por ciudad",
      precio: 12000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
    {
      id: "geo-03",
      categoria: "Geomarketing",
      nombre: "Selección de Ubicación Estratégica",
      descripcion: "Busca expansión sin ubicación definida. Identifica y prioriza las zonas idóneas para establecer el negocio dentro de una ciudad.",
      desglose: "Por ciudad",
      precio: 15000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
    {
      id: "geo-04",
      categoria: "Geomarketing",
      nombre: "Análisis de Potencial de Mercado",
      descripcion: "Tiene modelo, sin una ubicación. Evalúa la viabilidad macroeconómica y tamaño de mercado para decidir entrar a una nueva plaza.",
      desglose: "Por ciudad",
      precio: 20000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
    {
      id: "geo-05",
      categoria: "Geomarketing",
      nombre: "Geomarketing Táctico para Medios (OOH/ATL)",
      descripcion: "Estrategia publicitaria. Identifica corredores de alto flujo y zonas de concentración del target para ubicar espectaculares o activaciones.",
      desglose: "Por ciudad",
      precio: 15000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
    {
      id: "geo-06",
      categoria: "Geomarketing",
      nombre: "Inteligencia de Mercado y Perfilamiento",
      descripcion: "Negocio activo (general). Analiza la base de clientes para entender el alcance real y detectar nuevos mercados similares.",
      desglose: "Por ciudad",
      precio: 20000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
    {
      id: "geo-07",
      categoria: "Geomarketing",
      nombre: "Diagnóstico de Desempeño de Red",
      descripcion: "Múltiples PDV con ventas desiguales. Compara variables de entorno entre sucursales exitosas vs. bajas para aislar los factores de éxito.",
      desglose: "Por ciudad",
      precio: 30000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
    {
      id: "geo-08",
      categoria: "Geomarketing",
      nombre: "Revisión de domicilio",
      descripcion: "sdfghjkluygfvbhjkf",
      desglose: "",
      precio: 0,
      unidad: "visita",
      aporte_pm: 1000,
    },

    // ── Análisis en campo ───────────────────────────────────────────────────
    {
      id: "camp-01",
      categoria: "Análisis en campo",
      nombre: "Levantamiento de Factibilidad Técnica Inmobiliaria",
      descripcion: "Realizado por Arquitecto Perito. Analiza el terreno/local físicamente: uso de suelo, topografía, accesos, vicios ocultos y normatividad.",
      desglose: "Por predio",
      precio: 8000,
      unidad: "predio",
      aporte_pm: 1000,
    },
    {
      id: "camp-02",
      categoria: "Análisis en campo",
      nombre: "Mystery Shopper y Auditoría de Servicio",
      descripcion: "Evalúa la experiencia del cliente \"de incógnito\". Califica protocolos de venta, atención del personal, limpieza y tiempos de espera.",
      desglose: "Por visita",
      precio: 800,
      unidad: "visita",
      aporte_pm: 1000,
    },
    {
      id: "camp-03",
      categoria: "Análisis en campo",
      nombre: "Auditoría de Ejecución en Punto de Venta (Store Check)",
      descripcion: "Revisión técnica de la tienda. Verifica layout, exhibición de producto, señalética, inventarios visibles y cumplimiento de estándares de marca.",
      desglose: "Por sucursal",
      precio: 3000,
      unidad: "sucursal",
      aporte_pm: 1000,
    },
    {
      id: "camp-04",
      categoria: "Análisis en campo",
      nombre: "Aforos y flujo",
      descripcion: "Conteo manual de tráfico peatonal/vehicular.",
      desglose: "Por día",
      precio: 800,
      unidad: "día",
      aporte_pm: 1000,
    },
    {
      id: "camp-05",
      categoria: "Análisis en campo",
      nombre: "Análisis",
      descripcion: "",
      desglose: "",
      precio: 5000,
      unidad: "análisis",
      aporte_pm: 1000,
    },

    // ── Encuestas ───────────────────────────────────────────────────────────
    {
      id: "enc-01",
      categoria: "Encuestas",
      nombre: "Encuesta Nivel 1 (Flash)",
      descripcion: "Sondeo rápido en calle a transeúntes generales sin filtros.",
      desglose: "Por encuesta",
      precio: 40,
      unidad: "encuesta",
      aporte_pm: 800,
    },
    {
      id: "enc-02",
      categoria: "Encuestas",
      nombre: "Encuesta Nivel 2 (Estándar)",
      descripcion: "Cuestionario en zonas de afluencia con filtro demográfico básico.",
      desglose: "Por encuesta",
      precio: 70,
      unidad: "encuesta",
      aporte_pm: 800,
    },
    {
      id: "enc-03",
      categoria: "Encuestas",
      nombre: "Encuesta Nivel 3 (Perfilada)",
      descripcion: "Dirigida a usuarios con hábitos de consumo específicos; requiere filtro de selección.",
      desglose: "Por encuesta",
      precio: 150,
      unidad: "encuesta",
      aporte_pm: 800,
    },
    {
      id: "enc-04",
      categoria: "Encuestas",
      nombre: "Encuesta Nivel 4 (B2B/Nicho)",
      descripcion: "Visita a negocios o perfiles de difícil acceso y baja incidencia.",
      desglose: "Por encuesta",
      precio: 200,
      unidad: "encuesta",
      aporte_pm: 800,
    },
    {
      id: "enc-05",
      categoria: "Encuestas",
      nombre: "Digital Base Propia",
      descripcion: "Diseño, programación y envío a base de datos de clientes provista por el contratante.",
      desglose: "Por encuesta",
      precio: 30,
      unidad: "encuesta",
      aporte_pm: 800,
    },
    {
      id: "enc-06",
      categoria: "Encuestas",
      nombre: "Digital Panel Externo",
      descripcion: "Renta de audiencia online segmentada y garantizada por intereses/NSE a través de proveedor.",
      desglose: "Por encuesta",
      precio: 200,
      unidad: "encuesta",
      aporte_pm: 800,
    },
    {
      id: "enc-07",
      categoria: "Encuestas",
      nombre: "Supervisión virtual",
      descripcion: "Cumplimiento de las reglas de la encuesta y gestión de metas.",
      desglose: "Por plaza",
      precio: 800,
      unidad: "plaza",
      aporte_pm: 800,
    },

    // ── Entrevistas ─────────────────────────────────────────────────────────
    {
      id: "ent-01",
      categoria: "Entrevistas",
      nombre: "Entrevista Remota (Consumidor)",
      descripcion: "Videollamada con perfil general para explorar motivaciones (30-45 min).",
      desglose: "Por entrevista",
      precio: 500,
      unidad: "entrevista",
      aporte_pm: 800,
    },
    {
      id: "ent-02",
      categoria: "Entrevistas",
      nombre: "Entrevista Presencial (Consumidor)",
      descripcion: "Sesión física (café/domicilio) para análisis profundo de hábitos y lenguaje no verbal (45-60 min).",
      desglose: "Por entrevista",
      precio: 1500,
      unidad: "entrevista",
      aporte_pm: 800,
    },
    {
      id: "ent-03",
      categoria: "Entrevistas",
      nombre: "Entrevista de Nicho (Especializada)",
      descripcion: "Perfil de consumo difícil de encontrar o muy específico (Ej. Usuarios de marcas de lujo, veganos).",
      desglose: "Por entrevista",
      precio: 1500,
      unidad: "entrevista",
      aporte_pm: 800,
    },
    {
      id: "ent-04",
      categoria: "Entrevistas",
      nombre: "Entrevista B2B (Operativo/Gerencial)",
      descripcion: "Visita a decisores de mando medio en empresas (Ej. Gerentes de sucursal, Jefes de compras).",
      desglose: "Por entrevista",
      precio: 2000,
      unidad: "entrevista",
      aporte_pm: 800,
    },
    {
      id: "ent-05",
      categoria: "Entrevistas",
      nombre: "Entrevista B2B (Expertos/C-Level)",
      descripcion: "Sesión estratégica con Directivos, Dueños o Especialistas técnicos de alto nivel (Difícil acceso).",
      desglose: "Por entrevista",
      precio: 3000,
      unidad: "entrevista",
      aporte_pm: 800,
    },
    {
      id: "ent-06",
      categoria: "Entrevistas",
      nombre: "Reclutamiento",
      descripcion: "",
      desglose: "Por persona",
      precio: 1000,
      unidad: "persona",
      aporte_pm: 800,
    },

    // ── Focus Group ─────────────────────────────────────────────────────────
    {
      id: "fg-01",
      categoria: "Focus Group",
      nombre: "Reclutamiento (Base del cliente)",
      descripcion: "Únicamente contactar a las personas proporcionadas por el cliente.",
      desglose: "Por participante",
      precio: 0,
      unidad: "participante",
      aporte_pm: 500,
    },
    {
      id: "fg-02",
      categoria: "Focus Group",
      nombre: "Reclutamiento (General)",
      descripcion: "Búsqueda de perfil masivo o demográfico abierto (Ej. Amas de casa, Estudiantes).",
      desglose: "Por participante",
      precio: 400,
      unidad: "participante",
      aporte_pm: 500,
    },
    {
      id: "fg-03",
      categoria: "Focus Group",
      nombre: "Reclutamiento (Perfilado)",
      descripcion: "Búsqueda con filtros de consumo o hábitos específicos (Ej. Dueños de perros, Usuarios de iPhone).",
      desglose: "Por participante",
      precio: 800,
      unidad: "participante",
      aporte_pm: 500,
    },
    {
      id: "fg-04",
      categoria: "Focus Group",
      nombre: "Reclutamiento (Especializado)",
      descripcion: "Búsqueda de perfiles B2B, decisores de compra o nichos de difícil acceso (Ej. Médicos, Arquitectos).",
      desglose: "Por participante",
      precio: 800,
      unidad: "participante",
      aporte_pm: 500,
    },
    {
      id: "fg-05",
      categoria: "Focus Group",
      nombre: "Moderación y Análisis (Virtual)",
      descripcion: "Conducción de la sesión vía remota y elaboración de reporte de hallazgos.",
      desglose: "Por sesión",
      precio: 2500,
      unidad: "sesión",
      aporte_pm: 500,
    },
    {
      id: "fg-06",
      categoria: "Focus Group",
      nombre: "Moderación y Análisis (Presencial)",
      descripcion: "Conducción física de la dinámica (Sala/Gesell) y elaboración de reporte de hallazgos.",
      desglose: "Por sesión",
      precio: 3500,
      unidad: "sesión",
      aporte_pm: 500,
    },
    {
      id: "fg-07",
      categoria: "Focus Group",
      nombre: "Cámara de Gesell",
      descripcion: "",
      desglose: "Por sesión",
      precio: 3500,
      unidad: "sesión",
      aporte_pm: 500,
    },

    // ── Benchmarking ────────────────────────────────────────────────────────
    {
      id: "bench-01",
      categoria: "Benchmarking",
      nombre: "Benchmarking General",
      descripcion: "Análisis cualitativo de presencia digital: redes sociales, pilares de contenido, tono de voz, reputación (reviews) y estrategia visual, ubicaciones, etc.",
      desglose: "Por competidor",
      precio: 1500,
      unidad: "competidor",
      aporte_pm: 1000,
    },
    {
      id: "bench-02",
      categoria: "Benchmarking",
      nombre: "Benchmarking Comercial y de Precios",
      descripcion: "Análisis de datos duros: catálogo de productos, tabla comparativa de precios, mix de venta, promociones vigentes y costos de envío.",
      desglose: "Por competidor",
      precio: 2000,
      unidad: "competidor",
      aporte_pm: 1000,
    },
    {
      id: "bench-03",
      categoria: "Benchmarking",
      nombre: "Benchmarking Operativo (Mystery Shopping)",
      descripcion: "Investigación de campo/incógnito: visita física para evaluar atención, stock real, limpieza y protocolos de venta en sucursal.",
      desglose: "Por visita",
      precio: 800,
      unidad: "visita",
      aporte_pm: 1000,
    },
    {
      id: "bench-04",
      categoria: "Benchmarking",
      nombre: "Benchmarking Integral 360°",
      descripcion: "Radiografía completa que incluye los 4 módulos anteriores (General + Precios + Visita) para una visión total de la competencia.",
      desglose: "Por competidor",
      precio: 5000,
      unidad: "competidor",
      aporte_pm: 1000,
    },
    {
      id: "bench-05",
      categoria: "Benchmarking",
      nombre: "Social Listening",
      descripcion: "Análisis de redes y comunicación de la empresa.",
      desglose: "Por análisis",
      precio: 20000,
      unidad: "análisis",
      aporte_pm: 1000,
    },
    {
      id: "bench-06",
      categoria: "Benchmarking",
      nombre: "Herramienta Social Listening",
      descripcion: "",
      desglose: "Por proyecto",
      precio: 18000,
      unidad: "proyecto",
      aporte_pm: 1000,
    },

    // ── Búsqueda y recomendación PDV ────────────────────────────────────────
    {
      id: "pdv-01",
      categoria: "Búsqueda y recomendación PDV",
      nombre: "Búsqueda de locales",
      descripcion: "2 rondas de propuestas, una con los locales identificados y la segunda con feedback del cliente.",
      desglose: "Por ciudad",
      precio: 14000,
      unidad: "ciudad",
      aporte_pm: 1000,
    },
  ],
};
